{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.gms",
    "module": "google-services",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "google-services-4.4.0.jar",
          "url": "google-services-4.4.0.jar",
          "size": 40643,
          "sha512": "ff34dc9d1c6e1db87b7ecfa26d4e835a40eaa37a2c1861fe69c0c33017c133c728658f892c984cedd81af4c46e0bcd47a28e3039eb4b3532ef2cce09e497d091",
          "sha256": "af562d0b8b0e4f49f932ac3734f96ca145ae33b3ae8285714b6f6f936366e579",
          "sha1": "f6034e27702a31ac07d258e1347d7f3cf53e6a09",
          "md5": "2d9da1ffa53ca03f0e216609c2d3e939"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "strict-version-matcher-plugin",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.0.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "google-services-4.4.0.jar",
          "url": "google-services-4.4.0.jar",
          "size": 40643,
          "sha512": "ff34dc9d1c6e1db87b7ecfa26d4e835a40eaa37a2c1861fe69c0c33017c133c728658f892c984cedd81af4c46e0bcd47a28e3039eb4b3532ef2cce09e497d091",
          "sha256": "af562d0b8b0e4f49f932ac3734f96ca145ae33b3ae8285714b6f6f936366e579",
          "sha1": "f6034e27702a31ac07d258e1347d7f3cf53e6a09",
          "md5": "2d9da1ffa53ca03f0e216609c2d3e939"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google-services-4.4.0-javadoc.jar",
          "url": "google-services-4.4.0-javadoc.jar",
          "size": 261,
          "sha512": "d5584b8020339df74235964564f5000b27f45c6bab872a075eb2d9fb8b4239430a186a86523d0f53118e87f21c9d7cb370bb9be7b8144eb095afd677acd2154b",
          "sha256": "4baa8ab146fa42c78b6455dc621a2151887963ce8fbce4be21b71719c38161e8",
          "sha1": "950c99ca381c7dccf8e8834048ae45b663c864c9",
          "md5": "b7fd63aaee4483bc9b578a6a88268b73"
        },
        {
          "name": "google-services-4.4.0-javadoc.jar",
          "url": "google-services-4.4.0-javadoc.jar",
          "size": 261,
          "sha512": "d5584b8020339df74235964564f5000b27f45c6bab872a075eb2d9fb8b4239430a186a86523d0f53118e87f21c9d7cb370bb9be7b8144eb095afd677acd2154b",
          "sha256": "4baa8ab146fa42c78b6455dc621a2151887963ce8fbce4be21b71719c38161e8",
          "sha1": "950c99ca381c7dccf8e8834048ae45b663c864c9",
          "md5": "b7fd63aaee4483bc9b578a6a88268b73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google-services-4.4.0-sources.jar",
          "url": "google-services-4.4.0-sources.jar",
          "size": 6942,
          "sha512": "301a8fc984e0e3903cf016f9ecea7e86788cbbbce2a01ce930f00b07eca8594324bea868724c0713a54eaed138e34c79cd7d501cd2f703e1547d7935360e5ae6",
          "sha256": "e10281edc00ec9eb79c7a33dab60b3b26639b75cc765786755755a5c73534e94",
          "sha1": "3c3447505eaa6ea3626551da8c587fafab20d5c4",
          "md5": "03c4aa6a0520fca333e1dcef46182cd7"
        },
        {
          "name": "google-services-4.4.0-sources.jar",
          "url": "google-services-4.4.0-sources.jar",
          "size": 6942,
          "sha512": "301a8fc984e0e3903cf016f9ecea7e86788cbbbce2a01ce930f00b07eca8594324bea868724c0713a54eaed138e34c79cd7d501cd2f703e1547d7935360e5ae6",
          "sha256": "e10281edc00ec9eb79c7a33dab60b3b26639b75cc765786755755a5c73534e94",
          "sha1": "3c3447505eaa6ea3626551da8c587fafab20d5c4",
          "md5": "03c4aa6a0520fca333e1dcef46182cd7"
        }
      ]
    }
  ]
}
