{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-play-services",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "16.0.1"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.7.1.jar",
          "url": "kotlinx-coroutines-play-services-1.7.1.jar",
          "size": 13204,
          "sha512": "40ad603c9b7326baad8c66507f2f27342c4adfc9829368c86fe05c99256aa4c9f20246095d592f518e5478b559d08e458d18033cbf5daaf6089f4cef85570bb9",
          "sha256": "cea1a6c391ec5a38f2f5509d006c5d036bed71022275e1f6a7aedc735e3f3861",
          "sha1": "6333bad6f256e2ca7bc2908f586be7161a41618c",
          "md5": "763c3ac863c0733a0aa2da25e3ea0d69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "16.0.1"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.7.1.jar",
          "url": "kotlinx-coroutines-play-services-1.7.1.jar",
          "size": 13204,
          "sha512": "40ad603c9b7326baad8c66507f2f27342c4adfc9829368c86fe05c99256aa4c9f20246095d592f518e5478b559d08e458d18033cbf5daaf6089f4cef85570bb9",
          "sha256": "cea1a6c391ec5a38f2f5509d006c5d036bed71022275e1f6a7aedc735e3f3861",
          "sha1": "6333bad6f256e2ca7bc2908f586be7161a41618c",
          "md5": "763c3ac863c0733a0aa2da25e3ea0d69"
        }
      ]
    }
  ]
}
