{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ads",
    "module": "ads-adservices",
    "version": "1.0.0-beta05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.0.0-beta05"
          }
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.0.0-beta05.aar",
          "url": "ads-adservices-1.0.0-beta05.aar",
          "size": 86621,
          "sha512": "f59800ddc2b5bdcc93343f545fb91d86469a0d0fed69625e0fc102d9967497750c2c9afb7ee60696c1cf2ad956cfd4f1c832181f38c073215bf02770e2a718a3",
          "sha256": "0127578cdcedad7c8ece174814c6f4e302788e8f7bd14e833d919c1b7659d97d",
          "sha1": "d71f9480cad5dd22b7aee38ec0ec208359d63a23",
          "md5": "92d74b6b56e1d8aebd03d0706651f819"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.0.0-beta05"
          }
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.0.0-beta05.aar",
          "url": "ads-adservices-1.0.0-beta05.aar",
          "size": 86621,
          "sha512": "f59800ddc2b5bdcc93343f545fb91d86469a0d0fed69625e0fc102d9967497750c2c9afb7ee60696c1cf2ad956cfd4f1c832181f38c073215bf02770e2a718a3",
          "sha256": "0127578cdcedad7c8ece174814c6f4e302788e8f7bd14e833d919c1b7659d97d",
          "sha1": "d71f9480cad5dd22b7aee38ec0ec208359d63a23",
          "md5": "92d74b6b56e1d8aebd03d0706651f819"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices-java",
          "version": {
            "requires": "1.0.0-beta05"
          }
        }
      ],
      "files": [
        {
          "name": "ads-adservices-1.0.0-beta05-sources.jar",
          "url": "ads-adservices-1.0.0-beta05-sources.jar",
          "size": 46053,
          "sha512": "c9a95d997676dca4fab95c11f3b584b13d4234c7590779de509842404427264a26bed4f5111672fa0d1747a592cfe29b6722ea29eae4eb69cf0bcfa1299a03a4",
          "sha256": "1b228c78f1ab69e04093bf666f695a08b1c05d290bf8c898f3c70a1a0a1b53ba",
          "sha1": "d1bee637614b7927092da068ca8122ab85f3fd05",
          "md5": "a766d324cc293d4ccdc80a32afe7fe54"
        }
      ]
    }
  ]
}